backend:
  name: github
  repo: mattburns/mattburns.github.io
  branch: main

media_folder: static/img
public_folder: /img

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog/posts'
    create: true
    slug: "{{slug}}"
    path: "posts/{{slug}}/index"
    fields:
        - { label: 'Title', name: 'title', widget: 'string' }
        - { label: 'Publish Date', name: 'date', widget: 'datetime' }
        - { label: 'Author', name: 'author', widget: 'string', required: false, default: 'matt' }
        - { label: "Featured Image", name: "cover.image", widget: "image", required: true}
        - { label: 'Type', name: 'type', widget: 'string', required: true, default: 'post' }
        - { label: 'Body', name: 'body', widget: 'markdown' }